### PR TITLE
fix(actionbar): adjust padding to be 24 and include env inset calc

### PR DESCRIPTION
**Pull request by landondurnan**
## Describe the problem this PR addresses

https://github.com/square/maker/issues/169

## Describe the changes in this PR

Adjusted padding to be the desirable 24px all the way around (original design intent)
CleanShot 2021-11-10 at 15 18 28

Simplified the padding calculations with the [env()](https://developer.mozilla.org/en-US/docs/Web/CSS/env())

Added fallbacks in case env isn't supported.

## Other information

Previously we had a significant amount of extra padding added to get around the nefarious Safari "deadclick" zone. The usage of the env safe zone should have resolved that, but it looks some of those calculations resulted in roughly the same less than ideal positioning. Tested thoroughly on desktop + mobile on Chrome and Safari. Even did a built test on our PWA version:
Screen Shot 2021-11-17 at 10 51 09 AM

### CODE REVIEW

**Comment by landondurnan** [comment]
Appears to work as expected in Safari and Chrome. Looking into a lab deploy to test the "Save to homescreen" app-like experience.

**Comment by landondurnan** [comment]
Found some issues on desktop. Will re-open when they're fixed.

**Review by lokesh — APPROVED** [review]
The code refactor using `safe-area-inset-bottom` makes this 10x simpler. 

I didn't test myself, so approving with the assumption this was tested on mobile. It's worth testing in iOS Safari with both the address bar at the top and at the bottom (the new default in the latest major iOS release)

**Review by sohnj877 — APPROVED** [review]
LGTM 👍

**Pull request merged**
