### PR TITLE
feat(patterns): user defined theme level patterns

### PR DESCRIPTION
**Pull request by pretzelhammer**
## Describe the problem this PR addresses

https://github.com/square/maker/issues/269

## Describe the changes in this PR

- adds support for user-defined theme-level patterns to theming system
- adds default MText patterns: `headline`, `title`, `paragraph`, `label`
- adds default MButton patterns: `primary`, `secondary`, `tertiary`
- removes MHeading
- adds h1-h6 as supported values for MText `element` prop
- makes MText have 0 margin by default for all elements (including default `p` element)
- updates MText's `textAlign`, `textTransform`, `fontSize`, `fontStyle`, `fontFamily`, `lineHeight`, and `color` props to accept all valid CSS values for those properties
- prefixes all Maker public css vars with `maker`
- renames Maker public CSS var `--color-heading` to `--maker-color-heading`
- renames Maker public CSS var `--color-text` to `--maker-color-body`
- adds `heading`, `body`, and `label` objects to `fonts` object in theme definition which support `fontFamily` and `fontWeight` fields, customizing these fields customizes the default MText patterns as well as customizing how typography is rendered in all Maker components, e.g. MButton, MCalendar, MContainer, MModal, MSelect, MChoice, etc etc

## Migration Guide: v9 -> v10
- if you don't want to set a themeable prop but must pass some value then `''` (empty string) no longer works for that use-case, you must now explicitly pass `undefined`
- refactor`<m-heading>`s to `<m-text pattern="title">`s, copy over any other props & values as-is
- remove MHeading
- move any MHeading theming into the new `fonts.heading` part of the theme, e.g. change this:
```
heading: {
  fontFamily: 'whatever',
  fontWeight: 'whatever',
},
```
to this:
```
fonts: {
  heading: {
    fontFamily: 'whatever',
    fontWeight: 'whatever',
  },
},
```
- optional (but recommended, since it updates typography used in all Maker components) copy any MText theming into `fonts.body`, e.g. copy this:
```
text: {
  fontFamily: 'whatever',
  fontWeight: 'whatever',
},
```
to this:
```
fonts: {
  body: {
    fontFamily: 'whatever',
    fontWeight: 'whatever',
  },
},
```
- if necessary, re-add margin to `<m-text element="p">` (`p` is the default element)
- refactor these maker public CSS vars using this table:

| before | after |
|-|-|
--neutral-0 | --maker-color-neutral-0
--neutral-10 | --maker-color-neutral-10
--neutral-20 | --maker-color-neutral-20
--neutral-80 | --maker-color-neutral-80
--neutral-90 | --maker-color-neutral-90
--neutral-100 | --maker-color-neutral-100
--color-primary | --maker-color-primary
--color-background | --maker-color-background
--color-heading | --maker-color-heading
--maker-color-title | --maker-color-heading
--color-text | --maker-color-body
--maker-color-paragraph | --maker-color-body
--color-elevation | --maker-color-elevation
--color-overlay | --maker-color-overlay
--font-family-title | --maker-font-heading-font-family
--maker-font-family-title | --maker-font-heading-font-family
--font-weight-title | --maker-font-heading-font-weight
--maker-font-weight-title | --maker-font-heading-font-weight
--font-family-paragraph | --maker-font-body-font-family
--maker-font-family-paragraph | --maker-font-body-font-family
--font-weight-paragraph | --maker-font-body-font-weight
--maker-font-weight-paragraph | --maker-font-body-font-weight
--font-family-label | --maker-font-label-font-family
--maker-font-family-label | --maker-font-label-font-family
--font-weight-label | --maker-font-label-font-weight
--maker-font-weight-label | --maker-font-label-font-weight
- optional: refactor `<m-button variant="primary">` to `<m-button pattern="primary">` (for all button variants)

### CODE REVIEW

**Review by landondurnan — COMMENTED** [review]
Please don't merge this as-is. I have suggested changes to the data structure I'll submit as a PR against beta.

Also some brief testing with the theme lab and things aren't working as expected, not all the of code has been been converted correctly to work with these changes and it appears that are bugs with some of the default output.

**Comment by landondurnan** [comment]
I was testing the way to pass colors to the button patterns and it's not working as expected. Test branch here with setting explicit colors in the default theme, removed local color setting in the button doc dev, but only getting the resolvedColor form button.color, rather than the ones set in the pattern.

https://github.com/square/maker/compare/beta...beta-pattern-color-test

**Review by landondurnan — CHANGES_REQUESTED** [review]
Everything is looking good, but the Theme lab should be updated. It's currently not rendering due to the changes. If we can get that updated it should be good to go.

**Comment by pretzelhammer** [comment]
@landondurnan Themes lab has been fixed

**Review by landondurnan — APPROVED** [review]

**Pull request merged**
