### PR TITLE
feat: export standalone controls without form layout wrapper

### PR DESCRIPTION
**Pull request by pretzelhammer**
## Describe the problem this PR addresses

closes https://github.com/square/maker/issues/362

## Describe the changes in this PR

exports standalone controls without form layout wrapper

## Other information

nope

### CODE REVIEW

**Review by tatems — APPROVED** [review]

**Comment by laurenhu** [comment]
I'm worried this approach will be confusing - at least when it's applied to all the components. For instance, it's not clear at a glance from the styleguide which Input component to use, especially since they're now referenced as InputControl vs. InputFormItem in the docs, with the latter coming first. Appearance-wise, there's little difference between the two components, besides the error slot. I could see this making sense for radio, checkbox and toggle but not as much for Input, Select and PinInput. I would limit standalone controls to just the former three. Alternatively, we could also introduce an `align` prop to them, which we already have on Input to style the alignment of text. This would also allow us to standardize spacing for both configurations.

**Review by laurenhu — COMMENTED** [review]
I'm worried this approach will be confusing - at least when it's applied to all the components. For instance, it's not clear at a glance from the styleguide which Input component to use, especially since they're now referenced as InputControl vs. InputFormItem in the docs, with the latter coming first. Appearance-wise, there's little difference between the two components, besides the error slot. I could see this making sense for radio, checkbox and toggle but not as much for Input, Select and PinInput. I would limit standalone controls to just the former three. Alternatively, we could also introduce an align prop to them, which we already have on Input to style the alignment of text. This would also allow us to standardize spacing for both configurations.

**Comment by mattmewton** [comment]
Agree with @laurenhu 's comments, I think makes sense to keep the API as clean and simple as possible for consumers of Maker and the approach outlined in the above comment seems to align with that.

**Comment by pretzelhammer** [comment]
closing this PR because the associated issue has been closed, but if it's ever re-opened we can also re-open this pr

**Pull request closed without merging**
